# Generated by Django 5.1.4 on 2024-12-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_is_active_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
