# Generated by Django 5.1.4 on 2024-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_issuperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TimeField(),
        ),
    ]
