# Generated by Django 5.1.4 on 2024-12-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
