# Generated by Django 5.1.4 on 2024-12-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=5),
        ),
    ]
