# Generated by Django 5.1.4 on 2025-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_name_user_username_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+996552531101', max_length=255),
        ),
    ]
