# Generated by Django 5.1.4 on 2024-12-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_alter_event_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
    ]
