# Generated by Django 5.1.4 on 2024-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_currency_name_alter_event_date_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.CharField(max_length=255),
        ),
    ]
